// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibtfnbqtvrxqiouhwfii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlidGZuYnF0dnJ4cWlvdWh3ZmlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NzEzMDMsImV4cCI6MjA2MDU0NzMwM30.f9R9r6SOgRDb5ZumOk12nwaRZnyOXaLcIq-4pjADGY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);